### ISSUE TITLE
Simplify Code

### ISSUE THREAD

**Issue by Erfun76** [Optimox/HubMap#16]
hi,
thanks for your valuable work.
Will you simplify your code, so that researchers be able to lunch your code faster. to be specific the parts that you handle with preprocessing are designed to extract two-class data and there is not enough guidance on how to adapt other data to your code.

**Comment by Optimox** [comment]
Hello,

We are not planning to clean or package this specific code any further, but I would be happy to answer specific questions in order to help you getting started if needed.

Best
