### ISSUE TITLE
Problems when I use the code

### ISSUE THREAD

**Issue by LITTLEKKKK** [Optimox/HubMap#17]
The question about train_2 and train_4 folds, which WSI should I put in these fold?

**Comment by Optimox** [comment]
Please be more specific and explain clearly your problem if you wish to receive any help.

**Comment by LITTLEKKKK** [comment]
The file, params.py 
TIFF_PATH_4 = DATA_PATH + "train_4/"
TIFF_PATH_2 = DATA_PATH + "train_2/"
Is this a k-fold operation? If no, which WSI should be put in?

**Comment by Optimox** [comment]
Those are reduced version of the training set (2 times or 4 times), it's explained in the README, you can use `notebooks/Image downscaling.ipynb` to create the corresponding folders. You just need to set `FACTOR `to 2 or 4

**Comment by LITTLEKKKK** [comment]
Thanks a lot.
